### ISSUE TITLE
Custom ROM

### ISSUE THREAD

**Issue by jorgio** [MatusKysel/EMVemulator#5]
Dear MatusKysel,
I've  'Parse error: There was a problem parsing the package'  when try install app on Samsung Galaxy S3 (CyanogenMod 10.2).  I've try many versions of CyanogenMod, but only ver.10.1-10.2 can emulate after reading. And for this application need to be open card emulating possibility, isn't?  What custom ROM do you use for this app? Or how fix parse error for CyanogenMod 10.2?
Thank  you

**Comment by MatusKysel** [comment]
Hi, as you can see in manifest it requires at least Android API 19 (https://github.com/MatusKysel/EMVemulator/blob/master/AndroidManifest.xml#L8) or simply Android 4.4 which is the same as CM 11. But, because galaxy S3 has NXP NFC chip I am not sure if its possible to use HCE with CM 11 on this device (see http://stackoverflow.com/questions/24099849/host-based-card-emulation-any-guidance-please).

**Comment by jorgio** [comment]
This version fix parsing and emulate problem:
http://forum.xda-developers.com/galaxy-s3/development/i9300-to-n00t-bring-lte-fun-to-3g-t2886574
Which smartphone model and android version you used for this demo?
Thanks

**Comment by MatusKysel** [comment]
I have used nexus 4 and nexus 5 from version android 4.4 up to android 5.0.1.
